name: Build and Test

on:
  pull_request: {}

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write # Required to comment on pull requests
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Check dependencies for security vulnerabilities
        uses: actions/dependency-review-action@3c4e3dcb1aa7874d2c16be7d79418e9b7efd6261 # v4.8.2
        with:
          comment-summary-in-pr: on-failure
      - run: yarn install
      - run: yarn format
      - run: yarn build
      - run: yarn test
      # check the built bundle was committed
      - run: git diff --exit-code
